version: "3.2"
services:
  backend:
      container_name: nodejs
      restart: always
      build: ./
      ports:
        - "0.0.0.0:${PORT}:3333"
      volumes:
      - .:/app
      - ./error.log:/src/error.log
      links:
      - postgres
      - mongo
      - redis
      environment:
        DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_NAME}
  postgres:
      container_name: postgres
      image: postgres
      ports:
      - "5432:5432"
      env_file: 
      - .env
      volumes:
      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
      environment:
      - ${POSTGRES_PASSWORD}
      - ${POSTGRES_USER}
      - ${POSTGRES_NAME}
  mongo:
      container_name: mongo
      image: mongo
      ports:
      - "27017:27017"
      volumes:
      - ./data:/data/db
  redis:
      container_name: dev_redis
      image: redis:alpine
      ports:
      - "6379:6379"
      volumes:
      - ./data:/redis/db
